steps:
  # Get the latest version number and authors from commits
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Get Latest Version and Authors"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "feature/cws-7-configure-fix" ]]; then
          # Get the latest version number from the registry
          echo "🔍 Fetching existing tags from Artifact Registry..."
          ALL_TAGS=$$(gcloud artifacts docker images list us-docker.pkg.dev/prj-prd-cnb-workload/ar-workload-airflow-nonprod --include-tags --format="get(tags)")
          
          REGISTRY_VERSION=$$(echo "$$ALL_TAGS" | grep '3\.0\.2-cnb-v[0-9]*' | sort -V | tail -1)
          
          if [[ -z "$$REGISTRY_VERSION" ]]; then
            NEW_VERSION="3.0.2-cnb-v1"
            echo "📝 No existing version found, starting with v1"
          else
            VERSION_NUM=$$(echo "$$REGISTRY_VERSION" | grep -o '[0-9]*$$')
            NEW_VERSION_NUM=$$((VERSION_NUM + 1))
            NEW_VERSION="3.0.2-cnb-v$$NEW_VERSION_NUM"
            echo "📈 Incrementing version from $$REGISTRY_VERSION to $$NEW_VERSION"
          fi
        else
          NEW_VERSION="$SHORT_SHA"
        fi
        
        # Get unique authors from recent commits (last 50 commits)
        echo "👥 Extracting commit authors..."
        AUTHORS=$$(git log --pretty=format:"%an <%ae>" -50 | sort -u | tr '\n' ',' | sed 's/,$$//')
        
        # If no authors found, use default
        if [[ -z "$$AUTHORS" ]]; then
          AUTHORS="dev@ivedha.com"
          echo "⚠️  No authors found, using default"
        else
          echo "✅ Found authors: $$AUTHORS"
        fi
        
        # Write to a temporary file for next steps
        echo "$$NEW_VERSION" > /workspace/version.txt
        echo "$$AUTHORS" > /workspace/authors.txt
        echo "💾 Version and authors saved for next steps"

  # Build the Docker image with proper tagging and custom labels
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Read the version and authors from temporary files
        echo "📖 Reading version and authors from previous step..."
        NEW_VERSION=$$(cat /workspace/version.txt)
        AUTHORS=$$(cat /workspace/authors.txt)
        
        # Fallback if variables are empty
        if [[ -z "$$NEW_VERSION" ]]; then
          NEW_VERSION="$SHORT_SHA"
          echo "⚠️  Version not found, using commit SHA: $$NEW_VERSION"
        else
          echo "✅ Using version: $$NEW_VERSION"
        fi
        
        if [[ -z "$$AUTHORS" ]]; then
          AUTHORS="dev@ivedha.com"
          echo "⚠️  Authors not found, using default"
        else
          echo "✅ Using authors: $$AUTHORS"
        fi
        
        # Enable BuildKit for heredoc syntax support
        export DOCKER_BUILDKIT=1
        echo "🔨 Starting Docker build with BuildKit..."
        
        docker build \
          --build-arg AIRFLOW_VERSION=3.0.2 \
          --build-arg AIRFLOW_EXTRAS=aiobotocore,amazon,async,celery,cncf-kubernetes,common-io,common-messaging,docker,elasticsearch,fab,ftp,git,google,google-auth,graphviz,grpc,hashicorp,http,ldap,microsoft-azure,mysql,odbc,openlineage,pandas,postgres,redis,sendgrid,sftp,slack,snowflake,ssh,statsd,uv \
          --build-arg AIRFLOW_IMAGE_TYPE=prod \
          --build-arg AIRFLOW_UID=50000 \
          --build-arg BUILD_ID=$BUILD_ID \
          --build-arg COMMIT_SHA=$COMMIT_SHA \
          --label "com.ivedha.image.source=https://github.com/ivedha-tech/cnb-workload-airflow" \
          --label "com.ivedha.image.created=$$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          --label "com.ivedha.image.authors=$$AUTHORS" \
          --label "com.ivedha.image.url=us-docker.pkg.dev/prj-prd-cnb-workload/ar-workload-airflow-nonprod/airflow" \
          --label "com.ivedha.image.version=$$NEW_VERSION" \
          --label "com.ivedha.image.revision=$COMMIT_SHA" \
          --label "com.ivedha.image.vendor=Ivedha Inc" \
          --label "com.ivedha.image.title=CNB Workload Airflow Image" \
          --label "com.ivedha.image.description=Custom Apache Airflow image for CNB workload management" \
          --label "com.ivedha.image.ref.name=airflow" \
          --label "com.ivedha.main-image.build-id=$BUILD_ID" \
          --label "com.ivedha.main-image.commit-sha=$COMMIT_SHA" \
          --label "com.ivedha.branch=$BRANCH_NAME" \
          --label "com.ivedha.build-timestamp=$$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          -t "us-docker.pkg.dev/prj-prd-cnb-workload/ar-workload-airflow-nonprod/airflow:$$NEW_VERSION" \
          .

  # Push the Docker image to the registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Docker Image"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        NEW_VERSION=$$(cat /workspace/version.txt)
        echo "🚀 Pushing Docker image to Artifact Registry..."
        echo "📦 Image: us-docker.pkg.dev/prj-prd-cnb-workload/ar-workload-airflow-nonprod/airflow:$$NEW_VERSION"
        docker push "us-docker.pkg.dev/prj-prd-cnb-workload/ar-workload-airflow-nonprod/airflow:$$NEW_VERSION"
        echo "✅ Image pushed successfully!"
        
# Set timeout for the build (in seconds)
timeout: "3600s"

# Configure build options
options:
  # Enable Docker layer caching to speed up builds
  machineType: "E2_HIGHCPU_8"
  # Use a larger disk size for the build
  diskSizeGb: "100"
  # Enable logging
  logging: CLOUD_LOGGING_ONLY 